#!/usr/bin/env bash
set -uo pipefail

# PreCompact hook — save session context before compaction.
# 1. Copies transcript to $CC_STATE_DIR/.memory/checkpoints/pre-compact-<session-id>-<UTC>.jsonl
# 2. Builds $CC_STATE_DIR/.memory/handoff-latest.md from available on-disk state files
# 3. exit 0 always (non-blocking — PreCompact cannot block compaction)
#
# Style: bash wrapper + embedded python3 for JSON.

source "$(dirname "${BASH_SOURCE[0]}")/lib/cc-config.sh"

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
PAYLOAD="$(cat 2>/dev/null || true)"

python3 - "$PROJECT_ROOT" "$PAYLOAD" <<'PY'
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

project  = Path(sys.argv[1])
payload  = sys.argv[2].strip()

try:
    data = json.loads(payload) if payload else {}
except Exception:
    data = {}

stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
state_dir = os.environ.get("CC_STATE_DIR", ".cc_settings")
mem_dir = project / state_dir / ".memory"

# 1. Copy transcript to the checkpoints dir
transcript = data.get("transcript_path")
if transcript and Path(transcript).exists():
    try:
        session_id = Path(transcript).stem
        ckpt_dir = mem_dir / "checkpoints"
        ckpt_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(Path(transcript), ckpt_dir / f"pre-compact-{session_id}-{stamp}.jsonl")
    except Exception:
        pass

# 2. Build handoff-latest.md from available state files
state_sources = {
    "state": mem_dir / "STATE.md",
}

sections = [f"# Handoff — {stamp}\n\nGenerated by pre-compact-save hook.\n"]

if state_sources["state"].exists():
    sections.append(
        "## Current State\n\n"
        + state_sources["state"].read_text(errors="replace").strip()
        + "\n"
    )

if len(sections) > 1:
    try:
        mem_dir.mkdir(parents=True, exist_ok=True)
        (mem_dir / "handoff-latest.md").write_text("\n\n".join(sections))
    except Exception:
        pass

PY

exit 0
